version: '3.7'

volumes:
  db_data:
  drupal_data:

networks:
  db_network:
    driver: bridge
  frontend_network:
    driver: bridge

services:
  nginx:
    image: nginx:1.15.10
    container_name: nginx
    environment:
      NGINX_SERVER_ROOT: /drupal_app/web
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - drupal_data:/drupal_app
    networks:
      - frontend_network
    ports:
      - "5000:80"
    depends_on:
      - webapp
    restart: always

  # httpd:
  #   image: httpd:2.4.39
  #   container_name: httpd
  #   volumes:
  #     - ./config/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
  #     - drupal_data:/usr/local/apache2/htdocs/
  #   networks:
  #     - frontend_network
  #   ports:
  #     - "5005:80"
  #   depends_on:
  #     - webapp
  #   restart: always

  webapp:
    build:
      context: .
      dockerfile: DrupalDockerfile
    container_name: webapp
    env_file: .env
    volumes:
      - ./config/drupal/php.ini-development:/usr/local/etc/php/php.ini
      # - ./config/drupal/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./drupal_sync:/drupal_sync
      - ./gnatty_theme:/drupal_app/web/themes/contrib
      - drupal_data:/drupal_app
    networks:
      - db_network
      - frontend_network
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.15
    container_name: db
    env_file: .env
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql
      - ./db_shared:/docker-entrypoint-initdb.d/
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.7
  #   container_name: phpmyadmin
  #   env_file: .env
  #   environment:
  #     PMA_HOST: ${MYSQL_HOST}
  #     PMA_USER: ${MYSQL_USER}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD}
  #     PMA_ARBITRARY: 0
  #     PMA_PORT: 3306
  #   networks:
  #     - db_network
  #   volumes:
  #     - /sessions
  #   depends_on:
  #     - db
  #   restart: always
  #   ports:
  #     - "5001:80"

  # ssh:
  #   image: rastasheep/ubuntu-sshd:18.04
  #   env_file: .env
  #   container_name: ssh
  #   volumes:
  #     - drupal_data:/drupal_app
  #     - ./config/ssh/ssh_entrypoint.sh:/tmp/ssh_entrypoint.sh
  #   entrypoint: /tmp/ssh_entrypoint.sh
  #   depends_on:
  #     - webapp
  #   ports:
  #     - "5022:22"

