version: '3.7'

volumes:
  site_root:
  db_data:

networks:
  db_network:
    driver: bridge
  httpd_network:
    driver: bridge

services:
  nginx:
    image: nginx 
    container_name: Nginx
    ports:
      - "8088:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - httpd_network
    depends_on:
      - webapp-fpm
      - webapp-apache

  httpd:
    image: httpd
    container_name: Apache
    volumes:
      - ./config/apache/drupal.conf:/usr/local/apache2/conf/drupal.conf
    ports:
      - 1337:80
    networks:
      - httpd_network
    depends_on:
      - webapp-fpm
      - webapp-apache

  webapp-fpm:
    image: drupal:8.6.13-fpm
    container_name: Drupal-fpm
    ports:
      - 9999:80
    volumes:
      - site_root:/var/www/html/
    restart: always
    networks:
      - db_network
      - httpd_network
    depends_on:
      - db

  webapp-apache:
    image: drupal:8.6.13-apache
    container_name: Drupal-Apache
    ports:
      - 9000:80
    volumes:
      - site_root:/var/www/html/
    restart: always
    networks:
      - db_network
      - httpd_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: MySQL
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    restart: always
    ports:
      - 8888:80
    networks:
      - db_network
    volumes:
      - /sessions
    depends_on:
      - db
