version: '3.7'


volumes:
  site_root:
  db_data:


networks:
  db_network:
    driver: bridge
  httpd_network:
    driver: bridge


services:

  nginx:
    image: nginx:1.15.10
    container_name: nginx
    ports:
      - 5000:80
    volumes:
      # - site_root:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./drupal_app:/var/www/html
    networks:
      - httpd_network
    depends_on:
      - webapp

  webapp:
    image: drupal:8.6.13-fpm
    container_name: webapp
    env_file: .env
    volumes:
      - ./drupal_app:/var/www/html
      # - site_root:/var/www/html
      # - ./DrupalCode/config/drupal/settings.php:/tmp/settings.php

    restart: always
    networks:
      - db_network
      - httpd_network
    depends_on:
      - db

  db:
    image: mysql:8.0.15
    container_name: db
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    restart: always
    ports:
      - 8888:80
    networks:
      - db_network
    volumes:
      - /sessions
    depends_on:
      - db
