version: '3.7'

# services:
  # nginx:
  #   image: nginx 
  #   container_name: nginx_liblsu
  #   environment:
  #     - NGINX_PORT=80
  #   ports:
  #     - "8088:80"
  #   volumes:
  #     - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     # - ./public_html/:/var/www/html/:ro
  #   networks:
  #     - frontend
  # php:
  #   image: drupal:8.5.14-fpm
  #   container_name: drupal_liblsu
  #   volumes:
  #     - drupal_modules:/var/www/html/modules
  #     - drupal_profiles:/var/www/html/profiles
  #     - drupal_themes:/var/www/html/themes
  #     - drupal_sites:/var/www/html/sites
  #   expose:
  #     - 9000
  #   networks:
  #     - frontend
  #     - backend
  #   env_file: .env
  #   environment:
  #     DB_HOST: ${DATABASE_HOST}
  #     DB_USER: ${DATABASE_USER}
  #     DB_PASSWORD: ${DATABASE_PASSWORD}
  #     DB_NAME: ${DATABASE_NAME}
  #     DB_DRIVER: mysql
  #     UPLOAD_LIMIT: 20M
  #     MEMORY_LIMIT: 128M
  #     # VIRTUAL_HOST=eni-dev1.digitas.fr

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:

networks:
  db_network:
    driver: bridge
  httpd_network:
    driver: bridge

services:
  httpd:
    image: httpd
    container_name: Apache
    volumes:
      - ./public_html/:/var/www/html/
      - ./etc/apache2/sites-available:/etc/apache2/sites-available
    ports:
      - 1337:80
    networks:
      - httpd_network
    depends_on:
      - webapp

  webapp:
    image: drupal:8.6.13-apache
    container_name: Drupal
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
    networks:
      - db_network
      - httpd_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: MySQL
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    restart: always
    ports:
      - 8888:80
    networks:
      - db_network
    volumes:
      - /sessions
    depends_on:
      - db
