version: '3.7'

volumes:
  db_data:
  drupal_data:

networks:
  db_network:
    driver: bridge
  frontend_network:
    driver: bridge

services:
  nginx:
    image: nginx:1.15.10
    container_name: nginx
    environment:
      NGINX_SERVER_ROOT: /drupal_app/web
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./drupal_app:/drupal_app
    networks:
      - frontend_network
    ports:
      - "5000:80"
    depends_on:
      - webapp

  webapp:
    build:
      context: .
      dockerfile: DrupalDockerfile
    container_name: webapp
    env_file: .env
    volumes:
      - ./config/drupal/settings.php:/tmp/drupal_local_settings.php
      - ./config/drupal/drupal_entrypoint:/tmp/drupal_entrypoint
      - ./config/drupal/drupal_composer.json:/tmp/drupal_composer.json
      - ./drupal_sync:/drupal_sync
      - ./drupal_app:/drupal_app
      # - drupal_app:/drupal_app
    networks:
      - db_network
      - frontend_network
    depends_on:
      - db
    restart: always
    entrypoint: /tmp/drupal_entrypoint
    working_dir: /drupal_app

  db:
    image: mysql:8.0.15
    container_name: db
    env_file: .env
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 0
      PMA_PORT: 3306
    networks:
      - db_network
    volumes:
      - /sessions
    depends_on:
      - db
    restart: always
    ports:
      - "5001:80"

  ssh:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: ssh
    volumes:
      - ./drupal_app:/drupal_app
    depends_on:
      - webapp
    ports:
      - "5022:22"

