#!/usr/bin/env bash

set -e

# if no drupal directory, make drupal.  Otherwise, use the drupal you got.
if [ ! -d /drupal_app/web/sites/default ]; then
    echo "### Making drupal from scratch ###"

    # composer create-project drupal-composer/drupal-project:8.x-dev /drupal_app --stability dev --no-interaction --no-install
    # cp /tmp/drupal_composer.json /drupal_app/composer.json
    # composer update

    # the following line concats our settings on the drupal settings file
    # cat /tmp/drupal_local_settings.php >> /drupal_app/web/sites/default/settings.php
    # chown -R www-data:www-data /drupal_app
    # chown -R www-data:www-data /drupal_sync

else
    echo "### Using drupal from your drupal_app folder ###"
fi

php-fpm
